apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: nginx:1.13.6
    ports:
    - containerPort: 80
      hostPort: 80
    volumeMounts:
    - name: app-logs
      mountPath: /opt/logs
  volumes:
  - name: app-logs
    hostPath:
      path: /opt/hlogs